[phases.setup]
nixPkgs = [
    "python310",
    "gcc",
    "cmake",
    "libGL",
    "glib",
    "libxcb",
    "libSM",
    "libICE",
    "libX11",
    "libXext",
    "libXrender"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
