[phases.setup]
nixPkgs = ["python310"]
aptPkgs = ["libgl1-mesa-glx", "libglib2.0-0", "libxcb1", "libsm6", "libice6", "libx11-6", "libxext6", "libxrender1"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
